# Generated by Django 3.2.25 on 2024-08-09 05:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20240809_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='postalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=2),
        ),
    ]
